### ISSUE TITLE
Fallback fonts are not correct

### ISSUE THREAD

**Issue by jakeleventhal** [resend/react-email#1037]
### Describe the Bug

https://jsfiddle.net/oyec3awm/11/ this shows the correct fallback font families. The prop type is incorrect currently.

### Which package is affected (leave empty if unsure)

@react-email/components, @react-email/font

### Link to the code that reproduces this issue

https://jsfiddle.net/oyec3awm/11/

### To Reproduce

See fiddle

### Expected Behavior

Updated prop types

**Comment by gabrielmfern** [comment]
Can you please elaborate a bit more?

**Comment by jakeleventhal** [comment]
The jsfiddle i provided shows the proper fallback fonts that are supported by most clients (i.e. gmail)

The proptypes are incorrect in this package

**Comment by gabrielmfern** [comment]
@jakeleventhal We can't really add these just thinking on the support of a single email client, as some of the other email clients on our supported list don't really support the ones you mentioned. I'd rather have the fallback fonts only allow the ones we are sure work on all of the supported email clients rather than on only one.

Closing as not planned for now.
