### ISSUE TITLE
Failed to compile Error: ReactServerComponentsError ./src/app/preview/[slug]/page.tsx

### ISSUE THREAD

**Issue by jwarykowski** [resend/react-email#1041]
### Describe the Bug

If you install the latest versions of `react-email/components` and `react-email/render` the email dev server will fall over with the following error: 

```
./src/app/preview/[slug]/page.tsx
ReactServerComponentsError:

You're importing a component that imports react-dom/server. To fix it, render or return the content directly as a Server Component instead for perf and security.

The error was caused by importing '@react-email/render/dist/index.mjs' in './src/app/preview/[slug]/page.tsx'.

Maybe one of these should be marked as a client entry "use client":
./src/app/preview/[slug]/page.tsx
```

### Which package is affected (leave empty if unsure)

@react-email/components, @react-email/render

### Link to the code that reproduces this issue

-

### To Reproduce

Upgrade `components` and the `render` packages to the following versions (currently latest):

```
"@react-email/components": "0.0.11",
"@react-email/render": "0.0.9"
```

### Expected Behavior

No compile error should occur.

### What's your node version? (if relevant)

18.18.0

**Comment by gabrielmfern** [comment]
Are you using the `resend` SDK?

**Comment by sorokin-energi** [comment]
have the same issue when I'm trying to use `@react-email/tailwind@0.0.13-canary.1`

**Comment by Crateros** [comment]
Experiencing the same thing on Node v 18.3.0. I have done nothing fancy or custom, I followed the basic "getting started steps" and ran `npm run dev`.

**Comment by praisegeek** [comment]
Add this to your next.config.js 

 ```js
 experimental: {
    serverComponentsExternalPackages: [
      '@react-email/components',
      '@react-email/render',
      '@react-email/tailwind'
    ]
  }
  ```
  Reference: 
  https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages

**Comment by jwarykowski** [comment]
@praisegeek I've confirmed this work in my own setup 🙇 . @gabrielmfern I see you've raised the pull request, thanks for the lightning response, any indications as to when this is likely to be merged?

**Comment by tdurand** [comment]
FYI I just run into the same issue with a Next.js v14 app with a tailwind styled email, dependencies version:

```javascript
"@react-email/components": "0.0.11",
    "next": "14.0.3",
    "react": "18.2.0",
    "react-email": "1.9.5",
    "tailwindcss": "3.3.5",
    "typescript": "5.3.2"
```

**Comment by jwarykowski** [comment]
@gabrielmfern - just to note I can see the same issue on my project using the following versions:

```
"@react-email/components": "^0.0.11",
"@react-email/render": "^0.0.9",
"@react-email/tailwind": "0.0.13-canary.4"
```

Note I need to add the following to get around the `Failed to compile Error: ReactServerComponentsError ./src/app/preview/[slug]/page.tsx` [issue](https://github.com/resendlabs/react-email/issues/1041#issuecomment-1821901988). 

```
experimental: {
   serverComponentsExternalPackages: [
     '@react-email/components',
     '@react-email/render',
     '@react-email/tailwind'
   ]
 }
 ```
 
 Furthermore, I must wrap the `<Tailwind>` component directly around `<Head>`, previously this was not required, can you confirm this is intentional? 
 
 ```
 <Tailwind config={config}>
  <Head>
    ...
  </Head>
</Tailwind>
```

**Comment by gabrielmfern** [comment]
> @praisegeek I've confirmed this works in my own setup 🙇 . @gabrielmfern I see you've raised the pull request, thanks for the lightning response, any indications as to when this is likely to be merged?

Sorry for the delay, we'll try to merge as soon as we can but there are other things with a bit higher priority in our TO-DO list so I can't give you an indication yet, once we get this merged into canary and/or into stable we'll notify you guys.

**Comment by ajhswan** [comment]
Hi All, I've just come across react-email. Very cool implementation. I've got a react-remix app that I'm trying to add react-email too. I see the above fix relates to next js. I'm getting the exact same error and wondered if anyone could point me in a direction to resolve this issue using remix. using:
@remix-run/node:  1.10.1
@remix-run/react: 1.10.1
@remix-run/server-runtime: 1.10.1
@remix-run/architect: 1.10.1

**Comment by ajhswan** [comment]
@gabrielmfern Thank for the prompt response, saved me doing something very hacking. Yes the issue was with opening the preview app. Was using @react-email/render 0.0.10. Added script "email": "email dev --dir app/components/emails" and ran npm run email to start the preview app. Just released the preview app has nothing to do with my remix app. 

I uninstalled @react-email/render and installed react-email@2.0.0-canary.3 instead. Preview app seems to be working great. Send test email feature is awesome. Nice one.

Quick question and this might not be the place for it. Previously the npm run email using @react-email/render 0.0.10 would build the project inside of .react-email/ folder. Don't see that anymore. Where are the project files?

Thanks very much for your help

**Comment by gabrielmfern** [comment]
@ajhswan 

> Quick question and this might not be the place for it. Previously the npm run email using @react-email/render 0.0.10 would build the project inside of .react-email/ folder. Don't see that anymore. Where are the project files?

Yeah, so, the package that creates that created the `.react-email` was the `react-email` package with `1.x.x` version. 

> I uninstalled @react-email/render and installed react-email@2.0.0-canary.3 instead. Preview app seems to be working great. Send test email feature is awesome. Nice one.

This new `2.0.0` canary is our testing version for the PR we're working on which makes the preview app muuuch better.
I wouldn't recommend you use it yet until we release it out of canary `1.10.1` should do the trick, just recently released it and it should contain the fix for you, but if you still are going to use it lmk if you find any issues.
