### ISSUE TITLE
Button lineHeight not working

### ISSUE THREAD

**Issue by Hainesy** [resend/react-email#1304]
### Describe the Bug

Currently setting lineHeight on button styles seems to get overridden by a fixed 100%, i.e. this code is completely ignored:

`<Button href="..." style={{ lineHeight: '150%' }}>Do something</Button>`

### Which package is affected (leave empty if unsure)

@react-email/components

### Link to the code that reproduces this issue

N/A

### To Reproduce

See description

### Expected Behavior

See description

**Comment by gabrielmfern** [comment]
big off, going to get a PR fixing that

**Comment by thesaltygerman** [comment]
+1 I try the react email again v2.0. but more bugs than v1! with days and weeks to fix!

No more waste time, back to jsx-email. At least is stable.

**Comment by gabrielmfern** [comment]
Hey @thesaltygerman, I hope you are doing well

> +1 I try the react email again v2.0

This issue here has nothing to do with the v2 as going into v2 didn't change anything related to Buttons

> but more bugs than v1

I would say the opposite, we have come a long way since the last quarter of 2023 and we're getting
stabler by the day. Many improvements that I could list here for you and that you can find our changelog as well.

> with days and weeks to fix!

This I have to say is not exactly true. We get the fixes very soon but we haven't had the time
to improve our workflow very much, this means that the fixes get released in a slow manner.

I ask that you are patient with us as we're doing our best to get React Email into a better and better shape.
I can get the fixes quickly on PRs, but the Resend team can't quite get to it that fast. I understand this can
be frustrating but it is how it is for the time being and, again, I ask that you all be patient with us. 🙏🏻😊

**Comment by gabrielmfern** [comment]
Released on canary now on `@react-emai/button@0.0.14-canary.0`
