### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by JacobwBruce** [resend/react-email#1349]
### Describe the Bug

`<Img>` never displays an image in emails, always a broken link. This occurs both for my own project, and the starter code generated with 'npx create-email@latest'. Images will show up in the preview server, but when I send the email (both through SendGrid and manually from the preview server) Images are missing. I viewed the emails both through Spark, and Outlook. 
To be honest I wasn't sure whether to label this as a bug or not, as I'm not sure if I'm doing something wrong, but I couldn't find anything in the docs or issues about this. 

### Link to the code that reproduces this issue

https://github.com/JacobwBruce/react-email-starter

### To Reproduce

Run the starter code and send an email from the preview server

### Expected Behavior

Images to show

**Comment by gabrielmfern** [comment]
Hey @JacobwBruce, this is a pretty common misconception. Here's a piece from an improvement to the docs I made:

https://github.com/resend/react-email/blob/c6cbbf04d909358134faef9c2e2508463e7d417f/apps/docs/cli.mdx#L24-L42

Sadly the preview deployment for the docs on that branch seems to not be triggered, but reading this should be enough for you.

**Comment by JacobwBruce** [comment]
Awesome, thank you for clearing this up. I guess I could just link images in a Next.js /public directory?

Great library by the way!

**Comment by gabrielmfern** [comment]
> I guess I could just link images in a Next.js /public directory?

@JacobwBruce, yup, exactly. You can look into the source code for our demos for an example on how to do that. We use the `process.env.VERCEL_URL` for this, you can use an equivalent.

**Comment by DeepTitan** [comment]
I run this node script in order to create a SymLink between the static directory and my next js public directory:

`node -e "const fs=require('fs');const path=require('path');const publicPath=path.join(process.cwd(),'public');const staticPath=path.join(process.cwd(),'emails','static');try{if(fs.existsSync(staticPath)){fs.rmdirSync(staticPath,{recursive:true});}fs.symlinkSync(publicPath,staticPath,'junction');console.log('Symlink created successfully!');console.log(`${staticPath} now links to ${publicPath}`);}catch(error){console.error('Error creating symlink:',error.message);}"`

This fixes the issue for me as I can develop using the public folder and still see the images when I run `npx email dev`
