### ISSUE TITLE
Tailwind size utility not working as expected

### ISSUE THREAD

**Issue by CodingSam** [resend/react-email#1372]
### Describe the Bug

When using tailwind "size" classname, it is not recognised and results in class="size-X" in the html:
`<div class="size-8">test</div>`

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

https://github.com/CodingSam/react-email-tailwind-size-bug

### To Reproduce

1. Add any Tailwind "size-X" eg. "size-8" className to a element / component
2. run `npm dev`
3. check the generated HTML version for class="size-8"

### Expected Behavior

react-email should recognise the "size-X" classname and add the appropriate width and height style attributes. [Link](https://tailwindcss.com/docs/size) to tailwind "Size" documentation.

**Comment by gabrielmfern** [comment]
This is because we don't have the latest `3.4` version of Tailwind running, and since we only run our bundled version of it for the Tailwind component, we would need to update internally.

The issue with that is that the new versions of Tailwind require we use async APIs, and this could only be done with either support for server components or support for Suspense. So if we did update we would have to force users to either use `renderAsync` or bring in #1268 which is going to be a breaking change.

**Comment by CodingSam** [comment]
Alright, thank you for clarifying. As a temp fix, we have temporary downgraded the version of "eslint-plugin-tailwindcss" to "3.13.0" so that it does not suggest / warn about classes that are not yet supported.

**Comment by arthurdotwork** [comment]
Any news there? We'd really like to use new Tailwind utilities. 🙏

**Comment by gabrielmfern** [comment]
Should be fixed under [`@react-email/tailwind@1.0.0-canary.0`](https://github.com/resend/react-email/blob/canary/packages/tailwind/CHANGELOG.md#100-canary0)

**Comment by dylan-oleria** [comment]
Does the 1.0.0 release also facilitate pulling in versions of tailwindcss after `3.3.2`?
