### ISSUE TITLE
react-email and iOS are not compatible yet

### ISSUE THREAD

**Issue by SECHUBSYSTEM** [resend/react-email#1478]
### Describe the Bug

Hello guys, so I'm a full stack software engineer who's recently working on an email based project, I'm using react.email and postmark, however my styles and paddings aren't showing up right on all iOS I've checked, my mails look perfect on other OS but looks terrible on iOS. I'm referring to the gmail and apple iOS email clients.
![WhatsApp Image 2024-05-22 at 20 07 25_e5a0930c](https://github.com/resend/react-email/assets/106301523/c750b693-8453-418e-b537-68c286892e86)

### Which package is affected (leave empty if unsure)

@react-email/body, @react-email/components, @react-email/font, @react-email/head, @react-email/html, @react-email/tailwind, client, create-email, react-email

### Link to the code that reproduces this issue

https://screenrec.com/share/PGOwKprm60   the repo is a company repo and its private due to NDA

### To Reproduce

https://screenrec.com/share/PGOwKprm60

### Expected Behavior

https://screenrec.com/share/PGOwKprm60
![WhatsApp Image 2024-05-22 at 20 04 15_3f5055c9](https://github.com/resend/react-email/assets/106301523/3119e726-b16b-4d6a-b5ea-abc240a66041)
![WhatsApp Image 2024-05-22 at 20 05 11_192e53df](https://github.com/resend/react-email/assets/106301523/75b542aa-6bf6-4b68-b252-cea1e7bc3035)

### What's your node version? (if relevant)

>v20

**Comment by gabrielmfern** [comment]
Looking at the screenshot for your email template, I already notice two issues:
* Using `justify-content` and `align-items`
* Using `rem` instead of `px`

This is what is breaking it on Gmail iOS. This might be coming from a common misconception where people think that React Email converts stuff like `flex` into some other form that works under email HTML, but it doesn't. What it does is provide you with the few components that already have the best HTML possible, and then you can use so that you don't have to worry about these common use case ones. But you will still have to worry about email client support on styles and elements.

https://www.caniemail.com is an amazing resource you can use to go through your email templates and check for if they have good support for which email clients.

For the `rem` unit Tailwind uses, we have [a good starter configuration](https://react.email/docs/components/tailwind#tailwind-configuration-with-px-instead-of-rem) that overrides most of the places Tailwind will use `rem` so that it uses `px` instead.

I will close this issue as it isn't an actual issue as well, hope this clears it up for you.

**Comment by asadkhan2006** [comment]
> Looking at the screenshot for your email template, I already notice two issues:
> 
> * Using `justify-content` and `align-items`
> * Using `rem` instead of `px`
> 
> This is what is breaking it on Gmail iOS. This might be coming from a common misconception where people think that React Email converts stuff like `flex` into some other form that works under email HTML, but it doesn't. What it does is provide you with the few components that already have the best HTML possible, and then you can use so that you don't have to worry about these common use case ones. But you will still have to worry about email client support on styles and elements.
> 
> https://www.caniemail.com is an amazing resource you can use to go through your email templates and check for if they have good support for which email clients.
> 
> For the `rem` unit Tailwind uses, we have [a good starter configuration](https://react.email/docs/components/tailwind#tailwind-configuration-with-px-instead-of-rem) that overrides most of the places Tailwind will use `rem` so that it uses `px` instead.
> 
> I will close this issue as it isn't an actual issue as well, hope this clears it up for you.

but what we can do to avoid colour invert on IOS dark mode .
I have a problem when we switch the IOS mail to dark mode its changing my  all colours.
