### ISSUE TITLE
No image displayed when sending test email (<Img> component)

### ISSUE THREAD

**Issue by j-fdion** [resend/react-email#1695]
### Describe the Bug

The image is displayed in the preview app:
![image](https://github.com/user-attachments/assets/67ca7d14-f582-4147-88a4-350c46cd32df)

The image is not displayed in the outlook app (web or not)
outlook.office.com:
![image](https://github.com/user-attachments/assets/a23cb99b-ab03-483a-8988-a83a28b2895f)
installed app:
![image](https://github.com/user-attachments/assets/a2fe5a76-39df-48d3-a047-a194d945e20e)

### Which package is affected (leave empty if unsure)

@react-email/img

### Link to the code that reproduces this issue

https://react.email/docs/getting-started/automatic-setup

### To Reproduce

1. Install the getting started project
2. Send test email
3. Look at the broken image

### Expected Behavior

Image should be visible in the emails.

### What's your node version? (if relevant)

22.5.1

**Comment by gabrielmfern** [comment]
This is because the image is not hosted, the preview server only displays what it would be if it was published. If you want it to appear in after sending, you should use a public URL that the email client access properly.

For more info on this, take a look at the callout in the docs [here](https://react.email/docs/cli#where-can-i-place-my-static-files-for-previewing).

Closing as not planned.

**Comment by j-fdion** [comment]
Thank you for the explanation, I didn't find this part of the doc. I should have searched more thoroughly.
